services:
  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5454:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
