// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Shop Node Js Aws Serverless",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "Get a list of products",
        "description": "Get a list of products with all their properties",
        "tags": [
          "Products"
        ],
        "operationId": "getProductsList.get.products",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok response with object"
          }
        }
      },
      "post": {
        "summary": "Create a new product",
        "description": "Creates a new product passing post parameters",
        "tags": [
          "Products"
        ],
        "operationId": "postProducts.post.products",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok response with product inserted"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "Get products by id",
        "description": "Returns a product by id",
        "tags": [
          "Products"
        ],
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok response with object"
          },
          "400": {
            "description": "Product not found response"
          }
        }
      }
    }
  },
  "definitions": {
    "Response": {
      "properties": {
        "statusCode": {
          "title": "Response.statusCode",
          "type": "number"
        },
        "headers": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "Response.headers",
          "type": "object"
        },
        "body": {
          "title": "Response.body",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "body"
      ],
      "additionalProperties": false,
      "title": "Response",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "statusCode": {
          "title": "ErrorResponse.statusCode",
          "type": "number"
        },
        "headers": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "ErrorResponse.headers",
          "type": "object"
        },
        "body": {
          "title": "ErrorResponse.body",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "body"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "dg6etd0ogl.execute-api.eu-west-1.amazonaws.com",
  "schemes": [
    "https"
  ]
};