service: shop-service
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  stage: 'dev'
  region: eu-west-1
  architecture: 'arm64'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
plugins:
  - serverless-esbuild
  - serverless-aws-documentation
functions:
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get